services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Kutuphane.2026!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Library: "Server=sql,1433;Database=KutuphaneDb;User Id=sa;Password=Kutuphane.2026!;TrustServerCertificate=True"
    depends_on:
      - sql

volumes:
  sqldata:
    name: kutuphane-sql-data
    external: true