@host = http://localhost:5089

### Tüm kitaplar
GET {{host}}/books

### Yeni kitap ekle
POST {{host}}/books
Content-Type: application/json

{
  "title": "Saatleri Ayarlama Enstitüsü",
  "author": "Ahmet Hamdi Tanpınar"
}

### Eklenen kitabı getir
GET {{host}}/books/4